services:
  db:
    container_name: alyx-discord-db

  bot:
    image: ghcr.io/tawmy/alyx.discord:main
    container_name: alyx-discord
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATA_PROTECTION_CERTIFICATE: /mnt/cert/data-protection
      AUTH_AUTHORITY: https://auth.tawmy.dev/realms/xiv
      AUTH_AUDIENCE: alyx-discord
      NETSTONE_API_ROOT_URI: https://api.netstone.tawmy.dev
      NETSTONE_API_AUTHORITY: https://auth.tawmy.dev/realms/xiv
      NETSTONE_API_SCOPES: basic
      NETSTONE_API_CLIENT_ID: alyx-discord
    volumes:
      - /root/cert/alyx-discord:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: alyx.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  postgres_data:
    name: alyx-discord-db

networks:
  reverse-proxy:
    external: true