services:
  db:
    container_name: alyx-discord-db
    restart: unless-stopped

  bot:
    container_name: alyx-discord
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      STATUS_MESSAGE: "New: Protected from Lodestone outages!"
      NETSTONE_MAX_AGE_CHARACTER: "60" # one hour
      NETSTONE_MAX_AGE_CLASS_JOBS: "60" # one hour
      NETSTONE_MAX_AGE_MINIONS: "1080" # 18 hours
      NETSTONE_MAX_AGE_MOUNTS: "1080" # 18 hours
      NETSTONE_MAX_FREE_COMPANY: "10080" # one week
    networks:
      - default
      - caddy
    labels:
      caddy: alyx.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  postgres_data:
    name: alyx-discord-db
    external: true

networks:
  caddy:
    external: true