services:
  db:
    container_name: alyx-discord-db
    restart: unless-stopped

  bot:
    container_name: alyx-discord
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATA_PROTECTION_CERTIFICATE: /mnt/cert/data-protection
      STATUS_MESSAGE: "New: Protected from Lodestone outages!"
    volumes:
      - /root/cert/alyx-discord:/mnt/cert
    networks:
      - default
      - caddy
    labels:
      caddy: alyx.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  postgres_data:
    name: alyx-discord-db
    external: true

networks:
  caddy:
    external: true