services:
  db:
    labels:
      - dev.orbstack.domains=db.alyx.discord.local

  bot:
    image: alyx.discord
    build:
      context: .
      dockerfile: Alyx.Discord.Api/Dockerfile
    environment:
      DEBUG_GUILD_ID: 1284800895967559711
      STATUS_MESSAGE: "I'm in development!"
      AUTH_AUTHORITY: https://id.ffxiv.local/realms/eorzea-dev
      NETSTONE_API_ROOT_URI: https://api.netstone.local
      NETSTONE_API_AUTHORITY: https://id.ffxiv.local/realms/eorzea-dev
    volumes:
      - /Users/tawmy/Desktop/asp-keys/alyx-discord:/mnt/cert
    labels:
      - dev.orbstack.domains=alyx.discord.local

volumes:
  postgres_data:
    name: alyx-db