services:
  db:
    container_name: alyx.discord-db
  
  bot:
    container_name: alyx.discord
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1337:8080" # monitoring
    volumes:
      - /opt/certificates/alyx-discord:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: alyx.eorzea.online
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  postgres_data:
    name: alyx.discord-db
    external: true

networks:
  reverse-proxy:
    external: true