services:
  db:
    restart: on-failure
    labels:
      - dev.orbstack.domains=db.alyx.discord.local

  bot:
    environment:
      DEBUG_GUILD_ID: 1284800895967559711
      STATUS_MESSAGE: "I'm in development!"
      DATA_PROTECTION_CERTIFICATE: /mnt/cert/alyx-discord
    volumes:
      - /Users/tawmy/Desktop/cert/alyx-discord:/mnt/cert
    labels:
      - dev.orbstack.domains=alyx.discord.local
    ports:
      - "8086:8080"

volumes:
  postgres_data:
    name: alyx-postgres