services:
  db:
    container_name: alyx-discord-db

  bot:
    image: ghcr.io/tawmy/alyx.discord:main
    container_name: alyx-discord
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTH_AUTHORITY: https://dev.ffxiv.id/realms/eorzea
      NETSTONE_API_ROOT_URI: https://netstone.tawmy.dev
      NETSTONE_API_AUTHORITY: https://dev.ffxiv.id/realms/eorzea
    volumes:
      - /root/cert/alyx-discord:/mnt/cert
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: alyx.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  postgres_data:
    name: alyx-discord-db

networks:
  reverse-proxy:
    external: true