services:
  db:
    restart: on-failure
    labels:
      - dev.orbstack.domains=db.alyx.discord.local

  bot:
    environment:
      DEBUG_GUILD_ID: 1284800895967559711
      STATUS_MESSAGE: "I'm in development!"
    labels:
      - dev.orbstack.domains=alyx.discord.local

volumes:
  postgres_data:
    name: alyx-postgres