services:
  main:
    image: alyx.discord
    build:
      context: .
      dockerfile: Alyx.Discord.Api/Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      NETSTONE_API_CLIENT_ID: ${NETSTONE_API_CLIENT_ID}
      NETSTONE_API_CLIENT_SECRET: ${NETSTONE_API_CLIENT_SECRET}