services:
  db:
    container_name: alyx-discord-db
    restart: unless-stopped

  bot:
    container_name: alyx-discord
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      STATUS_MESSAGE: "v1.0.0: Character Sheets!"
      NETSTONE_API_ROOT_URI: https://api.netstone.tawmy.dev
      NETSTONE_API_AUTHORITY: https://auth.tawmy.dev/realms/xiv
      NETSTONE_API_SCOPES: netstone.api

volumes:
  postgres_data:
    name: alyx-discord-db
    external: true