# This is a generated file. Not intended for manual editing.
services:
  bot:
    build:
      context: "/Users/tawmy/Git/Alyx.Discord"
      dockerfile: "Alyx.Discord.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Alyx.Discord.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "alyx.discord:dev"
    ports: []
    volumes:
    - "/Users/tawmy/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/tawmy/Git/Alyx.Discord/Alyx.Discord.Api:/app:rw"
    - "/Users/tawmy/Git/Alyx.Discord:/src:rw"
    working_dir: "/app"
